name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label Upon Approval
    runs-on: ubuntu-latest
    steps:
      - uses: pullreminders/label-when-approved-action@v1
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "LGTM"
      
    
